@host = http://192.168.43.112:8000/api

### lihat semua user
GET {{host}}/lihat-semua-user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtYWlsQGdtYWlsLmNvbSIsImlhdCI6MTYxMzE0MzMyNywiZXhwIjoxNjEzMTQ1MTI3fQ.YCPd6Cv5xAur1-y57lDYO1-NH0ewGAx7lIRwqhS2ctk

### signup 
POST {{host}}/signup HTTP/1.1
Content-Type: application/json

{
    "first_name": "malik",
    "last_name": "siapa",
    "email": "email2@gmail.com",
    "password": "12345",
    "phone_number": "081"
}

### login
POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
    "email": "email@gmail.com",
    "password": "12345"
}
